version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: portfolio3-db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'

  web:
    build:
      context: .
      args:
        - MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - .:/myapp
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - RAILS_ENV=production
      - DATABASE_HOST=db
      - DATABASE_USERNAME=db_user
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}

volumes:
  postgres_data:
