default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'testing') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'testing') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

development:
  <<: *default
  database: portfolio3_development

test:
  <<: *default
  database: portfolio3_test

production:
  <<: *default
  database: portfolio3-db
  username: db_user
  password: <%= Rails.application.credentials.gcp[:db_password] %>
