# # make sure it provides disk persistence, as many don't.
# #
# # Similarly, if you deploy your application as a Docker container, you must
# # ensure the database is located in a persisted volume.
# production:
#   <<: *default
#   # database: path/to/persistent/storage/production.sqlite3

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: portfolio3
  password: portfolio3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portfolio3_development

test:
  <<: *default
  database: portfolio3_test

production:
  <<: *default
  database: 'portfolio3-db'
  username: 'db_user'
  password: <%= Rails.application.credentials.gcp[:db_password] %>
  host: '/cloudsql/portfolio3-446011:us-central1:portfolio3-cloudsql-instance'
