default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('RDS_USERNAME', 'testing') %>
  password: <%= ENV.fetch('RDS_PASSWORD', 'testing') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

development:
  <<: *default
  database: portfolio3_development

test:
  <<: *default
  database: portfolio3_test

production:
  url: <%= ENV['DATABASE_URL'] %>
